import { GoogleGenerativeAI } from "@google/generative-ai";
import OpenAI from "openai";

export interface GeneratePromptsOptions {
  transcriptText: string;
  timestampsJson: string;
  specialPrompt: string;
  aiProvider: "gemini" | "openai";
  aiModel?: string;
  batchSize?: number;
}

function buildSystemPrompt(
  specialPrompt: string,
  transcriptText: string,
  timestampsJson: string,
  batchSize: number
): string {
  return `${specialPrompt}

You are generating video prompts for a YouTube video based on the audio transcription.
Each prompt describes a visual scene for a video fragment that will be generated by an AI video generator.

Transcription text:
${transcriptText}

Timestamps JSON:
${timestampsJson}

Generate exactly the right number of video prompts to cover the entire narration.
Each prompt should be a detailed visual description of what should be shown during that segment.
Return ONLY a JSON array of strings, each string being one video prompt.
Generate prompts in batches of ${batchSize}.`;
}

function parsePromptsFromText(text: string): string[] | null {
  const jsonMatch = text.match(/\[[\s\S]*\]/);
  if (!jsonMatch) return null;
  try {
    return JSON.parse(jsonMatch[0]);
  } catch {
    return null;
  }
}

async function generateWithGemini(
  systemPrompt: string,
  batchSize: number,
  model: string
): Promise<string[]> {
  const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || "");
  const geminiModel = genAI.getGenerativeModel({ model });

  const allPrompts: string[] = [];
  let continueGenerating = true;
  let batchNum = 0;

  while (continueGenerating) {
    const userMessage =
      batchNum === 0
        ? `Generate the first ${batchSize} video prompts as a JSON array of strings.`
        : `Continue generating the next batch of video prompts starting from prompt #${allPrompts.length + 1}. Return a JSON array of strings. If there are no more prompts needed, return an empty array [].`;

    const result = await geminiModel.generateContent([systemPrompt, userMessage]);
    const text = result.response.text();

    const prompts = parsePromptsFromText(text);
    if (!prompts || prompts.length === 0) {
      continueGenerating = false;
    } else {
      allPrompts.push(...prompts);
      batchNum++;
      if (prompts.length < batchSize) {
        continueGenerating = false;
      }
    }
  }

  return allPrompts;
}

async function generateWithOpenAI(
  systemPrompt: string,
  batchSize: number,
  model: string
): Promise<string[]> {
  const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY || "" });

  const allPrompts: string[] = [];
  let continueGenerating = true;
  let batchNum = 0;

  while (continueGenerating) {
    const userMessage =
      batchNum === 0
        ? `Generate the first ${batchSize} video prompts as a JSON array of strings.`
        : `Continue generating the next batch of video prompts starting from prompt #${allPrompts.length + 1}. Return a JSON array of strings. If there are no more prompts needed, return an empty array [].`;

    const response = await openai.chat.completions.create({
      model,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userMessage },
      ],
      temperature: 0.7,
      max_tokens: 16000,
    });

    const text = response.choices[0]?.message?.content || "";

    const prompts = parsePromptsFromText(text);
    if (!prompts || prompts.length === 0) {
      continueGenerating = false;
    } else {
      allPrompts.push(...prompts);
      batchNum++;
      if (prompts.length < batchSize) {
        continueGenerating = false;
      }
    }
  }

  return allPrompts;
}

export async function generateVideoPrompts(
  options: GeneratePromptsOptions
): Promise<string[]> {
  const {
    transcriptText,
    timestampsJson,
    specialPrompt,
    aiProvider,
    aiModel,
    batchSize = 100,
  } = options;

  const systemPrompt = buildSystemPrompt(
    specialPrompt,
    transcriptText,
    timestampsJson,
    batchSize
  );

  if (aiProvider === "openai") {
    return generateWithOpenAI(systemPrompt, batchSize, aiModel || "gpt-4o");
  }

  return generateWithGemini(systemPrompt, batchSize, aiModel || "gemini-2.0-flash");
}
