import { GoogleGenerativeAI } from "@google/generative-ai";

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || "");

export interface GeneratePromptsOptions {
  transcriptText: string;
  timestampsJson: string;
  specialPrompt: string;
  batchSize?: number;
}

export async function generateVideoPrompts(
  options: GeneratePromptsOptions
): Promise<string[]> {
  const { transcriptText, timestampsJson, specialPrompt, batchSize = 100 } = options;

  const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });

  const systemPrompt = `${specialPrompt}

You are generating video prompts for a YouTube video based on the audio transcription.
Each prompt describes a visual scene for a video fragment that will be generated by an AI video generator.

Transcription text:
${transcriptText}

Timestamps JSON:
${timestampsJson}

Generate exactly the right number of video prompts to cover the entire narration.
Each prompt should be a detailed visual description of what should be shown during that segment.
Return ONLY a JSON array of strings, each string being one video prompt.
Generate prompts in batches of ${batchSize}.`;

  const allPrompts: string[] = [];
  let continueGenerating = true;
  let batchNum = 0;

  while (continueGenerating) {
    const userMessage =
      batchNum === 0
        ? `Generate the first ${batchSize} video prompts as a JSON array of strings.`
        : `Continue generating the next batch of video prompts starting from prompt #${allPrompts.length + 1}. Return a JSON array of strings. If there are no more prompts needed, return an empty array [].`;

    const result = await model.generateContent([systemPrompt, userMessage]);
    const text = result.response.text();

    const jsonMatch = text.match(/\[[\s\S]*\]/);
    if (!jsonMatch) break;

    try {
      const prompts: string[] = JSON.parse(jsonMatch[0]);
      if (prompts.length === 0) {
        continueGenerating = false;
      } else {
        allPrompts.push(...prompts);
        batchNum++;
        if (prompts.length < batchSize) {
          continueGenerating = false;
        }
      }
    } catch {
      break;
    }
  }

  return allPrompts;
}
